{"timestamp":"2025-07-27T17:56:40.684152","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-27T17:56:40.685168","level":"info","event":"Filling up the DagBag from /home/azureuser/cloudfiles/code/users/abhishekbatti2001/llmfinetuning_stackoverflow/airflow_home/dags/preprocessing_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-27T17:56:40.751960Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T17:56:40.752156Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T17:56:40.752253Z","level":"info","event":"Current task name:run_preprocessing","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T17:56:40.752330Z","level":"info","event":"Dag name:stackoverflow_data_preprocessing","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T17:56:40.797208Z","level":"error","event":"python: can't open file '/home/azureuser/cloudfiles/code/users/abhishekbatti2001/llmfinetuning_stackoverflow/airflow_home/src/preprocessing.py': [Errno 2] No such file or directory","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-27T17:56:40.799953","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"CalledProcessError","exc_value":"Command '['python', '/home/azureuser/cloudfiles/code/users/abhishekbatti2001/llmfinetuning_stackoverflow/airflow_home/src/preprocessing.py']' returned non-zero exit status 2.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/azureuser/cloudfiles/code/users/abhishekbatti2001/llmfinetuning_stackoverflow/airflow_home/dags/preprocessing_dag.py","lineno":18,"name":"run_preprocessing_script"},{"filename":"/anaconda/envs/azureml_py38/lib/python3.10/subprocess.py","lineno":526,"name":"run"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-27T17:56:40.831103Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T17:56:40.831285Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T17:56:40.831370Z","level":"info","event":"Task:<Task(PythonOperator): run_preprocessing>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T17:56:40.831446Z","level":"info","event":"Failure caused by Command '['python', '/home/azureuser/cloudfiles/code/users/abhishekbatti2001/llmfinetuning_stackoverflow/airflow_home/src/preprocessing.py']' returned non-zero exit status 2.","chan":"stdout","logger":"task"}
